services:
  memos:
    build:
      context: ..
      dockerfile: scripts/Dockerfile.dev
    container_name: memos-dev
    volumes:
      - ~/sophia-blog-data/:/var/opt/memos
    ports:
      - 5231:5230
    restart: unless-stopped
